### ISSUE TITLE
concat.sh example has a problem

### ISSUE THREAD

**Issue by swlemp** [transitive-bullshit/ffmpeg-gl-transition#53]
https://github.com/transitive-bullshit/ffmpeg-gl-transition/blob/master/concat.sh

There are 3 input videos, each of them are 4.00 seconds long.
That means we have 2 transitions.  And, each transition is set to 1 second.
The total duration of `out.mp4` should be (3 videos * 4 seconds) = 12 seconds.

Instead, the output from concat.sh is 10 seconds long, meaning we have shortened the video.
This doesn't make sense -- transitions logically aren't supposed to reduce the video duration.

Ping @transitive-bullshit

**Comment by transitive-bullshit** [comment]
The concat is working as intended given your description.

Transitions mean that they take up time in the output video equal to half of both of the input videos they're transitioning between, so they require the output video to be less time than the sum of the input videos.

Let me know if this doesn't make sense -- it unfortunately seems to be a common question, but there's really no other way it could work since portions of the output video combine parts of multiple input videos.

**Comment by swlemp** [comment]
@transitive-bullshit Look at any video editor; transitions either add to the duration of the video _or_ happen inside the end of 'Clip A' and start of 'Clip B', not affecting the duration.

I've never seen behavior like this package before.  I thought the point of it was to avoid filter graph monkey business when trying to do something simple.  Look at concat.sh, man.

**Comment by swlemp** [comment]
@transitive-bullshit Actually, this demo does it correctly (12 sec, not 10): https://github.com/transitive-bullshit/ffmpeg-concat/blob/master/media/example.mp4

If that package let me apply ffmpeg filters on the input videos and specify custom inputs instead of just files, I'd use it in a heartbeat, it would make things 100x simpler.

**Comment by swlemp** [comment]
I am strapped for time so I'll be using ffmpeg-concat.  Thanks for making these @transitive-bullshit , please send me an e-mail address so I can paypal.

**Comment by transitive-bullshit** [comment]
@swlemp I'm glad that `ffmpeg-concat` worked for your use case.

Feel free to send any donations to fisch0920@gmail.com -- it's definitely much appreciated 🙏 

Thanks!
