### ISSUE TITLE
rendering bug for some aspect ratios

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/ffmpeg-gl-transition#7]
There's currently an bug where some video dimensions result in warped, funky-looking transitions.

I'm not sure exactly what the bug is, but my best guess is that it has to do with how AVFrame represents its frame data.  It seems that AVFrame adds [padding](https://ffmpeg.org/doxygen/2.7/structAVFrame.html#aa52bfc6605f6a3059a0c3226cc0f6567) to each line to maximize use of SIMD.  We're definitely not accounting for this padding, and I think that's what's causing the issue for some video sizes.

Adding this here to track progress.

**Comment by nudja** [comment]
I have experienced this problem quite a lot on a mac.  If I change the aspect ratio of the files then the problem can go away but I have not formulated a pattern yet.

What I have noticed, if it helps, is that the default transition seems to work on all files that otherwise fail with a more complex transition.  Does that help?

**Comment by transitive-bullshit** [comment]
Yeah, I know why it's happening, just haven't had the time or motivation to fix it since I'm no longer actively using this in my project (switched to [ffmpeg-concat](https://github.com/transitive-bullshit/ffmpeg-concat)).

The reason it doesn't repro for the simple `fade` transition is because the fade transition maps each input pixel directly to an output pixel.

The problem happens because ffmpeg internally adds padding to each row of memory with some video resolutions, and this implementation doesn't take this into consideration.
